### ISSUE TITLE
Request : download from F-Droid

### ISSUE THREAD

**Issue by beatnickgr** [openchargemap/ocm-system#101]
I have installed the apk from Yalp Store but it crashes after
"Engaging awesomeness
Checking network
Loading maps"

It would be nice to have this open source project in the F-Droid, for the ones who don't have google accounts.

**Comment by docloy** [comment]
Are there plans to publish an OCM app in the f-droid store? Would be great to get the app without any google dependencies free and open source. Thanks in advance!

**Comment by webprofusion-chrisc** [comment]
Hi, no we will not be publishing the app to other app stores and eventually it will probably be offered entirely as a progressive web app without specific android/ios etc versions. The web app works from https://map.openchargemap.io using any recent mobile device and is the same as the android/iOS versions but uses mapbox/OSM as the map provider. As the app requires an active internet connection and does not have an offline mode there is only a moderate benefit to having it installed locally (vs cached in your browser).
