### ISSUE TITLE
Catalan Energy Institute (ICAEN) import format has changed

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#103]
It looks like the Catalan Energy Institute (ICAEN)  have changed to offer a real-time feed of charge points in Catalonia, which is now in JSON format instead of the CSV they used to use.

Details (in Catalan) at http://icaen.gencat.cat/web/.content/20_Energia/24_usos_energia/04_mobilitat/01_vehicle_electric/enllacos/20171218_ICAEN-Manual_consulta_PDR_WEB.pdf

I've already spotted that the https url the data is served from is not signed by a well-known provider, but other than that, the data looks good - if a little small. The data is also location-based, so a lot easier to parse for multiple connector types for each POI - which the old CSV format doesn't handle well.

I also found that the Ajuntement de Barcelona has another open dataset, details here:
http://opendata-ajuntament.barcelona.cat/data/ca/dataset/punts-recarrega-vehicles-electrics

Seems to be more complete, but there's known to be some listed there that have since been removed.

**Comment by webprofusion-chrisc** [comment]
Thanks for pointing this out. Currently the size of data set would not warrant the development & testing time (an hour or two) from my perspective but if you fancy trying to develop it yourself I can try to give some pointers.

**Comment by webprofusion-chrisc** [comment]
Closing old import issues.
