### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by cybersol795** [openchargemap/ocm-system#105]
Would anyone mind if I propose to edit your documentation? I am taking a technical writing course in university  and our assignment involves editing github project documentations to practice real world examples.
The goal is not to significantly change or remove any part of the technical information but to improve the structure of the writing or fix typos and grammatical issues. Edits may involve aspects like clarity and concision too.
It will really help me out if you allow me to contribute, make a few changes and submit a PR. Thanks!

**Comment by webprofusion-chrisc** [comment]
@cybersol795 yes, that would be great! Any help is much appreciated.

**Comment by cybersol795** [comment]
Thank you very much. Is there any specific reason that the documentation for DataModel.V3.md and BuildPrerequisites.md are separated from the original Readme.md? I was considering to move all the instructions to readme but was not sure if this major change is ok.

**Comment by webprofusion-chrisc** [comment]
@cybersol795 the build prerequisites could go into the readme, but datamodel.v3 I don't remember writing! There was a plan to migrate to a new data model but it never actually happened. The notes are relevant for planning though.

Where people commonly struggle with the lack of documentation is:
- information on what the project is and how it works
- information on how licensing works (large companies especially struggle to work out if they can use our info)
- information on using the API (some docs exist here but thye are incomplete and the v3 API is undocumented: https://openchargemap.org/site/develop/api
