### ISSUE TITLE
Add Korean Charger Database

### ISSUE THREAD

**Issue by Felger** [openchargemap/ocm-system#107]
The South Korean government provides charger list and current status (charging or free) etc.
URL: https://www.ev.or.kr/portal/monitor/chargerList

Documentation appears sparse, but here's what I've got:
To identify charger type see "skind" field, it's quite tricky.
01 : Chademo
02 : AC Type1
03 : Chademo + AC 3phase Type2
04 : CCS Type1
05 : CCS Type1 + Chademo
06:  CCS Type1 + Chademo + AC 3phase Type2
07 : AC3 phase type2

Charger power might be the "skindt" field, other fields may be reverse-engineer-able.

**Comment by zymurgic** [comment]
utime field is opening hours, in Korean.
snm field is the station name (Title)
x field is latitude
y field is longitude
sid field is the operators reference for that station

**Comment by webprofusion-chrisc** [comment]
Sorry I missed this, what is the license for this data? We can only import data that's explicitly licensed as Open Day or public domain, unless we have express permission from the source.
