### ISSUE TITLE
Additional Provider Bundesnetzagentur ?

### ISSUE THREAD

**Issue by autumnus** [openchargemap/ocm-system#109]
Probably this is an additional source for German charging stations:
(sadly just a regularly updated EXCEL file from a governmental office!)

https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulen/Ladesaeulenkarte_Datenbankauszug18.xlsx;jsessionid=5AA60F337832B692BBE808D5D7A7E4E8?__blob=publicationFile&v=3

Or did I just not find it?

**Comment by webprofusion-chrisc** [comment]
That's great, we'd just need to find out what their data license is and if the data is available in other formats.

**Comment by wanderzirkus** [comment]
Hi,

as I am from Germany myself (and actually writing an app currently for which I plan to use your great project - thanks for this in advance! :)), I'd love to see this source integrated. It also looks pretty complete for my place in bavaria.
As for the license: It is an "Attribution 4.0 International (CC BY 4.0)" (see https://creativecommons.org/licenses/by/4.0/deed.en) - should be Ok to use it though. But you have to mention "Bundesnetzagentur.de" anywhere when the data is used.

Let me know when the data is integrated - or - if you need any help let me know. :)

**Comment by webprofusion-chrisc** [comment]
Thanks! Is there a page which states that license? Also, is the data available in anything other than excel? I'm curious if this is something we would likely import repeatedly or just once.

**Comment by wanderzirkus** [comment]
Hi,

The license informations are stated here: https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulenkarte/Ladesaeulenkarte_node.html
I wasn't able to find an english version of it, but if you just scroll down you will find the name of the license written in a gray Box. You could also try Google translator. 
I also could not find another data source than the excel file, but I wrote an Email to them to ask if there is an api or something..

**Comment by webprofusion-chrisc** [comment]
@wanderzirkus thanks for your help. We have a general process for importing from excel sources but if there is an underlying database that the excel data is exported from then generally that's better for us, especially if we might import from it more than once.

**Comment by wanderzirkus** [comment]
Yeah, sure. But as I said, I am afraid there is only the excel. :(

**Comment by wanderzirkus** [comment]
Hey is there any progress here? So you need support in adding the source?

**Comment by webprofusion-chrisc** [comment]
Hi, I forgot to reply to this. As this is not an API data source (so most likely will not be worth the effort of building a repeatable import just for this data source) what we need is for the data to be transposed into our import template which can be downloaded from here:

https://github.com/openchargemap/ocm-docs/tree/master/DataImport/ImportTemplate

Current names to use for connection types etc can be found in the lists here:https://openchargemap.org/site/poi

**Comment by solarjoe** [comment]
Anyone working on this?

If not, I could put together a Python script using openpyxl to convert the xlsx from Bundesnetzagentur to the OCM ImportTemplace. Looks rather straight forward.

**Comment by autumnus** [comment]
I am sorry, but I do not have any time right now. So I am not working on that.

**Comment by solarjoe** [comment]
Ok, I am putting together a Python script to convert the Excel to the OCM ImportTemplace.

But I need some help, since I am not familiar with the plugs.
The Bundesnetzagentur file has the following plugs:

- 'AC Schuko'
- 'AC CEE 3 polig'
- 'DC CHAdeMO'
- 'Steckdose Typ 1'
- 'AC Steckdose Typ 2'
- 'DC Kupplung Combo'
- 'AC Kupplung Typ 2'
- 'AC CEE 5 polig'

The comment in the template states a lot more:

- J1772
- CHAdeMO
- BS1363 3 Pin 13 Amp
- Blue Commando (2P+E)
- LP Inductive
- SP Inductive
- Avcon Connector
- Tesla (Roadster)
- NEMA 5-20R
- NEMA 14-30
- NEMA 14-50
- Europlug 2-Pin (CEE 7/16)
- NEMA 6-20
- NEMA 6-15
- CEE 3 Pin
- CEE 5 Pin
- CEE+ 7 Pin
- XLR Plug (4 pin)
- NEMA 5-15R
- CEE 7/5
- Wireless Charging
- Mennekes (Type 2)
- SCAME Type 3C (Schnieder-Legrand)
- Tesla Supercharger
- CEE 7/4 - Schuko - Type F
- Type I (AS 3112)
- Tesla (Model S onwards)
- Tesla Battery Swap
- SAE Combo (DC Fast Charge J1772)
- CCS (Type 2 Version of Combined Coupler)
- IEC 60309 3-pin
- IEC 60309 5-pin
- SCAME Type 3A (Low Power)

Can someone tell me the equivalents to the chargers in the Bundesnetzagentur file?

**Comment by solarjoe** [comment]
A first shot without the plugs looks like
[ocm_import_BNA.xlsx](https://github.com/openchargemap/ocm-system/files/3439549/ocm_import_BNA.xlsx)

There are not that many columns in the BNA file.
I could not find equivalents to the following in the template:

Inbetriebnahmedatum (start date of operation)
Anschlussleistung [kW] (power total)
Art der Ladeeinrichtung (type of charging station, can be Fast Charge and Normal Charge)

Ideas?

**Comment by webprofusion-chrisc** [comment]
HI, thanks for attempting to convert this spreadsheet. Did we determine that the data is definitely licensed for general use?

If you don't have specific information for a data field it can be left out, the only situations where we will not import a row is:
- we have an existing charging location nearby
- the equipment details do not specify any information about connection type or power level.

Regarding connector types, full details of our known reference data is available from our API: http://api.openchargemap.io/v2/referencedata - see the ConnectionTypes collection (Title field)

**Comment by solarjoe** [comment]
As already mentioned above, the license is [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/deed.en), stated at the bottom of [this page](https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulenkarte/Ladesaeulenkarte_node.html).

**Comment by solarjoe** [comment]
I had a look and could map some of the BNA plug names to the OCM names:
`AC Schuko` > `CEE 7/4 - Schuko - Type F`
`AC CEE 3 polig` > `CEE 3 Pin`
`DC CHAdeMO` > `CHAdeMO`
`AC CEE 5 polig` > `CEE 5 Pin`

But I could not find these:
`Steckdose Typ 1`
`AC Steckdose Typ 2`
`DC Kupplung Combo`
`AC Kupplung Typ 2`
        
Do some of them map to `CCS (Type 2 Version of Combined Coupler)` or `Mennekes (Type 2)` ?

Ideas?

**Comment by webprofusion-chrisc** [comment]
Hi, 
I believe `AC Steckdose Typ 2` (AC Socket Type 2) would be `Mennekes (Type 2)`, I can't tell with the other ones though.

**Comment by estation** [comment]
- Steckdose Typ 1 >> This shouldn't exist in reality on chargepoints. Type 1 clutch shoul
- AC Steckdose Typ 2 > "MENNEKES Type 2"
- AC Kupplung Typ 2 > This should be a MENNEKES Type 2 with fixed cable.
- DC Kupplung Combo > CCS Type 2 

- exist on cars.

-

**Comment by Razzeee** [comment]
The source website changed and the file no longer seems to be at that url. I also couldn't find a new link on their website.

**Comment by autumnus** [comment]
Hi.
I have a few links:
[https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulenkarte/Ladesaeulenkarte_node.html](https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulenkarte/Ladesaeulenkarte_node.html
)
which is a map

And on this page there is a link:
[https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulen/Ladesaeulenkarte_Datenbankauszug29.xlsx?__blob=publicationFile&v=3](https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/HandelundVertrieb/Ladesaeulen/Ladesaeulenkarte_Datenbankauszug29.xlsx?__blob=publicationFile&v=3)
This link can change, dependent on the version of the file

**Comment by johan12345** [comment]
Has anyone continued to work on this?

The current link for the data description is at:
https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/E-Mobilitaet/Ladesaeulenkarte/start.html
and it can be downloaded as Excel file at
https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/E_Mobilitaet/Ladesaeulenkarte_Datenbankauszug.xlsx?__blob=publicationFile&v=7
or CSV at
https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/E_Mobilitaet/Ladesaeulenkarte_DatenbankauszugCSV.csv?__blob=publicationFile&v=21

Mapping of abovementioned plugs should be the following:
 ```
'AC Schuko' -> 'CEE 7/4 - Schuko - Type F'
'AC CEE 3 polig' -> 'CEE 3 Pin'
'DC CHAdeMO' -> 'CHAdeMO'
'Steckdose Typ 1' -> 'Type 1 (J1772)'
'AC Steckdose Typ 2' -> 'Type 2 (Tethered Connector) '
'DC Kupplung Combo' -> 'CCS (Type 2)'
'AC Kupplung Typ 2' -> 'Type 2 (Socket Only)'
'AC CEE 5 polig' -> 'CEE 5 Pin'
```

**Comment by johan12345** [comment]
I also found a way to retrieve the same data as JSON from the API that powers the map on the Bundesnetzagentur website:

https://services6.arcgis.com/6jU7RmJig2Wwo1b0/arcgis/rest/services/Ladesaeulenregister/FeatureServer/7/query?f=json&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A5.0986681876%2C%22ymin%22%3A47.0416812506%2C%22xmax%22%3A15.6601907311%2C%22ymax%22%3A55.1299067491%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&inSR=25832&outFields=*&returnCentroid=false&returnExceededLimitFeatures=false&maxRecordCountFactor=3&outSR=25832&resultType=tile

The number of items seems to match the Excel file, and the included data also appears to be basically the same. So maybe this could be used for a direct import.

**Comment by webprofusion-chrisc** [comment]
Hi, I've previously stated on our forum that I'm not planning to develop any further data imports and instead we will rely on crowdsourced data: https://community.openchargemap.org/t/retirement-of-data-imports-etc/307 so in general, if we don't have crowdsourced data then that means we don't have a crowd (users in that country) and that's OK.

If someone provides the fully populated XLS in our import template format then I'll do a one-off import (this won't be repeated). This will also required creating/matching any network operators we don't currently have.

If someone wants to develop a data import for this I can try to provide some basic guidance. Our other automated imports are here: https://github.com/openchargemap/ocm-system/tree/master/Import/OCM.Import.Common/Providers - you can see from the dates which are maintained and which aren't. Basically all these do is (repeatably) map from a source and give us a list of populated POIs as a result, when we then run de-duplication etc on.
