### ISSUE TITLE
Apple Maps issue on Submission Under Review

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#111]
On the main Openchargemap website, If a location is of status of Submission Under Review, they don't show as a pin on the Apple Maps panel on the Map tab, which makes it difficult to check that the submitted location is feasible (not in the sea, etc)

**Comment by webprofusion-chrisc** [comment]
Thanks, this transition is a work in progress.

**Comment by webprofusion-chrisc** [comment]
See also https://github.com/openchargemap/ocm-system/issues/112

**Comment by webprofusion-chrisc** [comment]
Map tab in website view of POi now shows a default marker at the search position, so if a POI is not yet published you'll see a grey marker for the position instead (also when doing searches around a location).
