### ISSUE TITLE
Mapping migration: use OSM where practical

### ISSUE THREAD

**Issue by webprofusion-chrisc** [openchargemap/ocm-system#112]
Historically most of the mapping UI (Maps, place searches) has been provided by the Google Maps javacript sdk. As Google Maps now charges for Places searches in particular (and static maps views, dynamic maps to some extent) out API bill would be prohubitively expensive. For that reason biilable API calls need to be moved to an alternative service where possible.

Currently the least expensive option is Apple Maps, so a transition to MapKitJS has begun. The Android and iOS native apps will continue to use Google Maps (an experimental build using MapKitJS prove to slow to use).

Some basic map operations have been transitions and the current plans is now to get the the searches working again.

Once we are back to normal the plan is to implement the main POI Editor (Add/Edit locations) in the app (https://map.openchargemap.io) to favour mobile users and to give us one editor codebase.

**Comment by beatnickgr** [comment]
If we want the app to be in the F-Droid, we should prefer OpenStreetMap, not Apple...

**Comment by webprofusion-chrisc** [comment]
@beatnickgr thanks, we can probably offer MapBox (which is OSM data) but I'm not aware of a completely open source native mapping solution and we will still want to offer user the option of choosing Google Maps (we removed Apple Maps from the Android version).

**Comment by beatnickgr** [comment]
Thanks for your quick answer.
We're 2 osm cartographers discussing how to (correctly) map the charging stations, and i want to invite you to our group. I used your app's name for the link because i couldn't find another one available https://t.me/openchargemap

**Comment by webprofusion-chrisc** [comment]
Thanks, if we could discuss it here that would be great. I have switched the web version of the app over to Mapbox (OSM)

**Comment by webprofusion-chrisc** [comment]
@beatnickgr on the topic of OSM ev charging here are a few links from past discussions:

https://wiki.openstreetmap.org/wiki/OpenChargeMap

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station

**Comment by beatnickgr** [comment]
Tag https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station is completely outdated. You might see I have edited the discussion page but received no answer.
As a faster way of communication, I've joined the OSM telegram group and from there created a separated group for chargers. It would be a pleasure if you joined our informal conversation in that group.

**Comment by beatnickgr** [comment]
The new group for Electric Vehicles is now listed in the wiki https://wiki.openstreetmap.org/wiki/List_of_OSM_centric_Telegram_accounts

**Comment by zymurgic** [comment]
Looks like the mapbox api key is giving 401 Unauthorized at the moment

**Comment by webprofusion-chrisc** [comment]
@zymurgic thanks I changed that a few days ago (MapBox have graciously given us 6 months free, which is great because we've done 124K map view as 30K  geocodes in the last 6 days). I suspect your browser is caching the javascript from before the key change?

**Comment by zymurgic** [comment]
Ah yes. I normally just try in a different browser, but that too had cached the old javascript with the old key as well.

**Comment by poliantoIT** [comment]
Hi, from some day in the page https://openchargemap.org/site/poi/add the map is blank. Problably it is somting due to the recent changes, can you fix it please?
Bye Antonio

**Comment by webprofusion-chrisc** [comment]
@poliantoit thanks, I'd forgotten that page uses the older API key, I'll get that fixed.

**Comment by poliantoIT** [comment]
Thanks, I noticed it 5 days ago but I thought that it was something on which you were working on so I waited until after Easter to report the issue. ( I've been some days totally offline)

**Comment by webprofusion-chrisc** [comment]
@poliantoit sorry I wasn't blaming you for not reporting it, I think we have a larger issue with feedback and engagement with the overall community of users.
