### ISSUE TITLE
Json response characterset does not seem to utf-8

### ISSUE THREAD

**Issue by richardrevesz** [openchargemap/ocm-system#117]
I'm building an app that relies on several apis, including this one.
Google apis are working fine for eg.
This one's response is a mess, like the app would not read the data correctly, it expects utf-8.
When I try from Mozilla it works as charm and returns Unicode as text encoding, but I'm aware that it may differ.
I've tried to get the string from the data array as utf-8, 7, 32, Unicode, ASCII, Latin1(Iso), I've tried to ignore the first x bytes. 
I've tried to add https harder values for content-type: application/json and charset: utf-8.
No luck at all. I'm struggling for a day with it now, please save me from this frustration.

**Comment by richardrevesz** [comment]
My request:
https://api.openchargemap.io/v3/poi/?output=json&latitude=47.46716&longitude=19.04562&distanceunit=KM&maxresults=1

The expected response is the one you get if you click on the link.

The response I get in Unity 2018.2.16f1 with UnityWebRequest myRequest, myRequest.dowloadHandler.text:
�X�n�F�/��P�ikʤL��7Y�v�رbY3�
rh�-�ßf��6�`"���r / 佶�II��d��d�0�]]���W�����Q�к�j]@��8�I�e>7�Z�7�ݮ��Ol˽�����y��
�]g8����Z�KS"h�Fk"Vt�Y���8
Ý�Qd*�#��0�α��#Ãt!�����g�Trqz�{�ND�6��0�Q�0d�t��L�ʇMB��t(�Nd�EH}<W"�'E�"r�偩Pkjݒ8%!hS0��شvR@��=�J0OQ�3��$��(q�j-7̣���@�a� T�_G	�&��ԨvJ ��1	J{��C�c	C�h�b<�fV:Y@�m�p+*b��Я7�\�˚
���V)���H�a1p�����1�(d5�$ALq�����"�.)֛G+5�
��Ƣۭ}�����ʠ�Ԛp����F�jM��
�/�����%Z��ū��"�����b����꼃��V�=\ �_Vs	J�'�

**Comment by webprofusion-chrisc** [comment]
Hi Richard, that's an interesting one! The API has been running for about 8 years and this is the first time anyone has reported such a thing. I'll investigate today and get back to you.

Is your Unity http request running via C# or a built in component? Mac or Windows?

**Comment by webprofusion-chrisc** [comment]
I see you mentioned UnityWebRequest, it's possible it's struggling with our gzip/deflate compression, I'll check.

**Comment by webprofusion-chrisc** [comment]
Hi, I've updated out API to allow clients that don't support either gzip or deflate compression, so this should work for you now. 

Unity was passing an Accept-Encoding header but it wasn't compression related and our API assumes DEFLATE support if you don't support GZIP. I'm sure there would be a way to allow gzip encoding (which gives you a faster download) as it has been a standard for a long time.

**Comment by richardrevesz** [comment]
Great, the string is valid now, thank you very much!
My next issue:
Unity's JSON utility doesn't support top level serialized json.
So it's unable to understand this: [{result},{result}]
But it would be able to read it like this: {"results":[{result},{result}]}.
I'm aware it's violating current API's structure, but if you could make it unity case sensitive...
Can you, could you do that please?

**Comment by webprofusion-chrisc** [comment]
Hi, no sorry but you can just read the results into a string then concatenate to get it into the shape you want (most c# users use the Newtonsoft.Json which is actually what generated this output).

```cs
 string apiResponse = request.downloadHandler.text;
 string json = "{\"results\":" + apiResponse + "}";

// now parse the json
// see https://github.com/openchargemap/ocm-system/tree/master/API/OCM.Net/OCM.API.Model/Base for actual c# model

**Comment by richardrevesz** [comment]
Thank you, I've had a similar idea, what I was trying to suppose is full Unity compatibility out of the box :)
But I'll just go with it for now.
Your help is greatly appreciated.
Best,
Richard
