### ISSUE TITLE
initial zoom level and location on website POI screen is wrong.

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#118]
Example: https://openchargemap.org/site/poi/details/121521

Initially, the Apple Maps integration will zoom in on the correct location, then instantly zoom out once it's loaded other nearby POIs. It looks like it then zooms out and re-centres the map on what appears to be the centroid of the loaded POIs, because if you zoom in again, you don't get to the original location, just back to the same vague locality, which may be tens of km away.

**Comment by webprofusion-chrisc** [comment]
Thanks, the apple MapKitJS doesn't provide a zoom method, just a fit to a map extent. We're using the apple map because everything else costs lots of money :) I'll look into it.

Don't suppose you want to try cloning ocm-app and see if you can fix? Current Mapping provider is set in environment.ts
