### ISSUE TITLE
Impossible to add a location

### ISSUE THREAD

**Issue by claudiobonora** [openchargemap/ocm-system#119]
Is it still possible to add a location?
After filling in the form, I click on the preview button but nothing happens and there is no button to save. Furthermore the box where there should be the map on which to drag is empty.
I've tried with Chrome and Firefox from desktop and smartphone.
Thanks for your help.

**Comment by webprofusion-chrisc** [comment]
Interesting! I can confirm that nobody else reporting this just now and that its working for me in both Firefox and Chrome. Can you try clearing your cache and if that makes no difference try it in Private/Incoginto mode to confirm no caching. If that still fails please check your browser console (dev tools console) for javascript errors and report them here if you can.
