### ISSUE TITLE
 ocm-system/Website/OCM.MVC/Views/Widget/_GeoChartWidget.cshtml doesn't colour in Russia

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#120]
ocm-system/Website/OCM.MVC/Views/Widget/_GeoChartWidget.cshtml 

It seems that Russian Federation / Russia (ISO code: RU) isn't being coloured in.

The data does make it into the JSON at

https://api.openchargemap.io/widgets/databrowser/datasummary.ashx
but somehow it doesn't get matched up when colouring in the country polygons.

**Comment by webprofusion-chrisc** [comment]
Thanks, I'm surprised this still works actually, it's had a good innings. I'll probably replace it with something mapboxy at some point unless anyone else wants to have a go.

**Comment by webprofusion-chrisc** [comment]
Fixed, was matching on country name instead of iso code.
