### ISSUE TITLE
adding operator in Hungary

### ISSUE THREAD

**Issue by csbhjd** [openchargemap/ocm-system#122]
Hi,

I am looking for a way to add an operator in Hungary. Could you describe the steps needed to do this?

thanks,
Csaba

**Comment by webprofusion-chrisc** [comment]
Hi, sorry I missed this notification. Please provide the details of the operations (Name, website) that you wish to add here, then it will be added by an administrator.

**Comment by csbhjd** [comment]
Hi,

Thanks for getting back to me.

The company details are the following:

Name: E.ON Hungary
website: www.eon.hu

In the OCM system our company in other regions are referred to as E.ON (DK) or, E.ON CZ, so E.ON (HU) would be suitable.

Thanks.

[E-mail-signature-layerbar]

Kind regards


Csaba Hajdu
Back Office
Product Support
E-fleet, E-Mobility
M +36 30 595 3278
E csaba.hajdu@eon-hungaria.com<mailto:csaba.hajdu@eon-hungaria.com>

E.ON Energiakereskedelmi Kft.
Váci str. 17.
1134 Budapest
www.eon.hu<http://www.eon.hu/>

Please consider the environment before printing this e-mail.

If You are not the intended and authorized recipient of this e-mail, please delete it immediately. The emailing system of the Employer shall be used only for business purposes, personal use is strictly prohibited. Without prior and expressed consent of the Employer any misuse or distribution of the content of this e-mail is prohibited, unlawful and entails legal consequences. Employer is entitled (pursuant to the Labour Code) to monitor emails and their attachments sent and received from the email address solely intended for business purposes, as those may include confidential information related to the company’s business activities. Employer will treat the content of the emails confidentially, which may only be disclosed to the Compliance Officer, staff involved in compliance investigation, E.ON Corporate Audit, the Information Security Officer or any delegate, and the Fraud Investigation Unit.

**Comment by webprofusion-chrisc** [comment]
Thanks, that's added now
