### ISSUE TITLE
www.openchargemap.org giving cloudflare errors

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#123]
Origin DNS error
What happened?

You've requested a page on a website (www.openchargemap.org) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.openchargemap.org). 

works as openchargemap.org, but not www.openchargemap.org

**Comment by webprofusion-chrisc** [comment]
Interesting! Is this in a normal browser (not a script) and is it repeatable? Scripts could have an issue of they don't declare a proper user agent.

I switched on CloudFlare caching in front of bothtl the website and API to reduce unnecessary repeated queries and to reduce the data transfer bill.

**Comment by zymurgic** [comment]
Firefox.  Identical with Google Chrome or Safari.
I have IPv6 of course. You might not.

**Comment by webprofusion-chrisc** [comment]
Still had the .org on non-cloudflare dns which upset the dns cname redirection. Seems good now.
