### ISSUE TITLE
Alperia becomes Neogy

### ISSUE THREAD

**Issue by poliantoIT** [openchargemap/ocm-system#124]
Hi,
from the 01/07 the Italian operator Alpera has changed name in to Neogy.
These are the new contacts: https://www.neogy.it info(at)neogy.it tel. 800 832 855 .
Is it possible to update automatically the existing points of charge with the new info?
If it would be possible also to update automatically with something like "find Alperia and change in to Neogy" the name of the existing points of charge it will be great!
Bye Antonio

**Comment by webprofusion-chrisc** [comment]
Hi, we can rename the existing operator easily as that's just a single database entry that the charge points are linked to, if there is other text (like in the title) that might not be as easy to change.

**Comment by webprofusion-chrisc** [comment]
Operator renamed/updated now.
