### ISSUE TITLE
Additional providers

### ISSUE THREAD

**Issue by solarjoe** [openchargemap/ocm-system#127]
Hello,

which additional providers is OCM working width?

I am [working on a Python script](https://github.com/openchargemap/ocm-system/issues/109) to parse the Bundesnetzagentur file, which will provide some info on many charging stations in Germany (~9000).

Are there plans to cooperate with other providers like

- https://www.lemnet.org/de (available as GPX, could be parsed)
- https://chargemap.com/ (Commercial, API?)
- https://www.goingelectric.de/stromtankstellen/api/ (API)
- querying OpenStreetMap for `amenity=charging_station`, done [here](http://www.flosm.de/html/POI-Karte.html?lat=49.4764030&lon=9.22133622&r=125349.79&st=1&sw=chargingbike,chargingcar,chargingscooter,chargingstation,chargingtruck,chargingwheelchair) 
or `fuel:electricity=yes` 
- https://wiki.openstreetmap.org/wiki/OpenChargeMap#Other_OpenChargeMap_-_OpenStreetMap_Integration

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for your interest and for looking at new imports.

Nobody is actively working on new data imports (as far as I know I'm the only person who has ever built one but some users do appear to submit info to us using robotic form submissions).

In all cases we need to agree licensing up front with the data source, then we need to consider if the data is a good fit (how relevant is it, how outdated could it be, is any of it verifiable, how much do we already have). We cannot use any commercial data sources as our data must be openly licensed for redistribution. Their data license must allow us to mix the data within our own dataset.

So in all cases:
- ask the data source if we can include their data and what license it should be under. Capture the agreement (email chain etc). Require formal permission.
- check how much of the data we already have, if we already have most of the data can the remainder be entered manually?
- is the data detailed enough? We need to know the position, approx address, charging network, equipment details (at least some info on connector type and power levels).

**Comment by webprofusion-chrisc** [comment]
It's also worth noting that it is absolutely critical that data we import does not contain people's home chargers. Once the data is in our database it is copied to hundreds of locations for various uses and we have no control over it after that. Open Charge Map is intended for official/dedicated charging infrastructure only (not home chargers, even if they are shared with the public) and we will likely remove any non-conforming locations in the future.

**Comment by webprofusion-chrisc** [comment]
Closing this issue as we will now only implement OCPI or other standard imports going forward,
