### ISSUE TITLE
Import from UK National Chargepoint Registry only imports one connector

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#130]
When the UK National Chargepoint Registry import is run, and when it encounters a charge device with multiple connectors, it will only import one of them.

Therefore, with most AC/DC rapid chargers that have three connectors, it may only import the first one it encounters, which is often the AC connector, leaving the Chademo and CCS connectors behind.

**Comment by webprofusion-chrisc** [comment]
Thanks I'll check it out.

**Comment by zymurgic** [comment]
Working as expected now
