### ISSUE TITLE
Statistics page is not updated

### ISSUE THREAD

**Issue by tdilo** [openchargemap/ocm-system#135]
It looks like the [statistics](https://openchargemap.org/site/stats) page is not updated anymore. This may only apply to the "Last 90 Days" sections, I am not sure about the other data.

**Comment by webprofusion-chrisc** [comment]
Thanks, I think I forgot to re schedule the background task that does that after a server move a while ago.

**Comment by webprofusion-chrisc** [comment]
Fixed now.
