### ISSUE TITLE
Web: Login on home doesn't Login to forum

### ISSUE THREAD

**Issue by Leftaf** [openchargemap/ocm-system#14]
Hi Christopher do you have the same issue.

I'm login at the Homepage
![09-08-2013 10-24-04](https://f.cloud.github.com/assets/2380560/937056/4e78fcfc-00cd-11e3-8b97-c155fd3494d1.png)
but when I change to the forum
![09-08-2013 10-26-29](https://f.cloud.github.com/assets/2380560/937113/b3004d68-00cf-11e3-9a63-bd64882d0482.png)
I'm not login

If I try to login via Twitter it fails
![09-08-2013 10-43-49](https://f.cloud.github.com/assets/2380560/937119/ec3dceac-00cf-11e3-8de3-eb55487bfa18.png)

**Comment by webprofusion-chrisc** [comment]
Closing old issue. Forum has been retired for Google+ community.
