### ISSUE TITLE
API v3 POI call returns invalid results when filtering by operatorid

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#140]
https://api.openchargemap.io/v3/poi/?output=json&OperatorID=20,3315&maxresults=5500

This, according to the specs, should return up to 5500 results of all listings for Charge your Car and Chargeplace Scotland combined in one file.

In actual fact, it doesn't appear to filter by OperatorID at all, and just returns the latest 5500 results from the system.

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this. Some case sensitivity had snuck into the parameter parsing so operatorid=20,3315 worked but OperatorID=20,3315 didn't.
