### ISSUE TITLE
Login: session gets dropped randomly

### ISSUE THREAD

**Issue by tdilo** [openchargemap/ocm-system#142]
The login session gets dropped randomly when reloading the page for any reason. For example, when clicking on "Add a location" after logging in, the resulting page load may either leave you logged in, or appear to log you out. The same happens when using the "Add additional equipment" button. If you then decide to sign in again from the "poi/add" page, you get redirected to https://openchargemap.org/site/poi and all data entered is lost.

This issue also manifests itself when simply reloading the main page (https://openchargemap.org/site) over and over again, which will show the "sign in" menu entry on about half of the page loads, and "my profile" for the rest of the time.

**Comment by webprofusion-chrisc** [comment]
Thanks! I'd upped the number of worker processes for the website yesterday which would normalyl nor be a problem but with the move to aspnet core 3.0 the sessions are not shared between the processes by default (now I know!) so it depended on which worker process handled the request. Have reduced the worker process count until this is resolved.
