### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by stanvass** [openchargemap/ocm-system#146]
Hello, the API appears to be down. Doesn't respond, or when it responds it's a 524 error, CloudFlare error (can't connect to source), and this apparently: https://i.imgur.com/Q7EXjX6.png

**Comment by webprofusion-chrisc** [comment]
Hi Stan, thanks. I made a change yesterday that broke our caching layer which then leads to meltdown as everyone tries to download our entire database directly from the backend SQL server. Fixed now.

Please see also this API key announcement: https://community.openchargemap.org/t/notice-api-will-shortly-require-an-api-key-for-regular-usage/29

**Comment by stanvass** [comment]
Hello, 

Thank you for your response, I'll implement the key.

However the API is down again. What is the expected availability today and over the next few days. Ongoing problems?

**Comment by webprofusion-chrisc** [comment]
Hi Stan, in an effort to reduce the load on the main API server I moved our MongoDB cache to a new (AWS Ubuntu) linux server, however after working well for 3 hours the system shut down, presumably an automated update. I've switched the caching back to our normal setup now.

**Comment by webprofusion-chrisc** [comment]
See also proposal for self-hosted API clones: https://github.com/openchargemap/ocm-system/issues/148
