### ISSUE TITLE
OCM API down?

### ISSUE THREAD

**Issue by JohannaSte** [openchargemap/ocm-system#147]
Hello,

I did not know where to write my request, since openchargemap.org is not available, and so the contact information is not visible for me.

Anyone else got issues while trying to reach the website and/or API? What can I do or who do I need to contact to gather further information?

Best regards,
Johanna

**Comment by stanvass** [comment]
I'm an API user. Yeah, they have some ongoing issues. It was down yesterday for about 10-15 hours. Couple of hours ago it was up, now it's down again.

**Comment by webprofusion-chrisc** [comment]
@JohannaSte thanks, yes we had problems with our MongoDB caching layer again (this time a server move to Ubuntu on AWS that worked for a few hours until the server shut itself down), normal service has resumed.

**Comment by webprofusion-chrisc** [comment]
See also proposal for self hosted API clones: https://github.com/openchargemap/ocm-system/issues/148
