### ISSUE TITLE
API: Heuristic for auto calculation of Level based on power etc

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#154]
It seems that the API is now changing submitted entries to a Level.ID of 2 for everything, even where the PowerKW is known and Level.ID is specified as 3.
This means that on the maps many of the DC rapid chargers show up in green rather than orange.

How to reproduce bug:
Edit a location that has Level 3 connectors, eg. POI 135304
Make sure that Level is set to 3 in the main web site editing form
Submit changes.
Read the API results or enter editor again, LevelID is set to 2 on the entries you've just changed.

**Comment by webprofusion-chrisc** [comment]
Thanks, the API now computes Power (kW) if we know the voltage/amps etc but not the kW, and it then computes the Level (loosely based on kW bands or voltage, there doesn't seem to be an exact definition for levels vs kw). Calculating where to break between level 2 and level 3 seems a bit tricky but I guess DC is a clue.

**Comment by webprofusion-chrisc** [comment]
But yes there is a bug because high kw with a voltage of 400 is currently being set as level 2.

**Comment by webprofusion-chrisc** [comment]
@zymurgic so I've updated the logic now to behave a little better but happy to debate the correct behaviour. Ultimately I'd like to remove the burden of specifying information you don't know from the user, Level being a good example. Ideally we'd limit it down to Power kW (max) and Connection type to limit the amount of information that can be wrong.

The current code for deciding level is here: https://github.com/openchargemap/ocm-system/blob/5d2525b2b9896b0a5ae6373ac1c07e8e10987493/API/OCM.Net/OCM.API.Core/Common/Extensions/ConnectionInfo.cs#L69 happy to debate it.

**Comment by webprofusion-chrisc** [comment]
p.s. here is the current UI and API output for that example POI for reference:

https://openchargemap.org/site/poi/details/135304

https://api.openchargemap.io/v3/poi?chargepointid=135304

**Comment by zymurgic** [comment]
Yes, Agree that most users don't know current and voltage limits, but that are far more likely to know power levels.
Harmonised European power grids tend to specify 400V as a phase-to-phase voltage on three-phase, when each phase's phase-to-neutral voltage is defined at about 230V. and that code doesn't really cope with the typical 43kW AC type 2 charging. (though ComputePowerkW() seems to get it right)
I'll see if I can come up with a fix that handles three-phase AC in ComputeChargingLevel()

**Comment by zymurgic** [comment]
See Pull Request #155

**Comment by webprofusion-chrisc** [comment]
Thanks. I'm also acutely aware that this change has been sprung without notice, it's come about because the new editor (in the map app) doesn't let the user specify Level (https://github.com/openchargemap/ocm-app/issues/11) but some consumers may still require the information. 

Future versions of the API (v4 perhaps) might drop some legacy data fields that we don't want to hang onto and leave things like power bands etc to the consumer/client apps.
