### ISSUE TITLE
Data Import Template

### ISSUE THREAD

**Issue by aa0d** [openchargemap/ocm-system#157]
Hi,
I'm trying to upload a larger amount of charging locations (around 200). It has been previously mentioned that its possible to use the ImportTemplate at:
https://github.com/openchargemap/ocm-docs/tree/master/DataImport/ImportTemplate
I'm not entirely sure how to use the template though. Should i simply edit it and push it to some branch or can i upload the template somewhere?

**Comment by webprofusion-chrisc** [comment]
Yes, you could fill out the template - best to fill out 10 rows or so then share it here for review to check the content is OK. Once filled out I can perform an import using it, it's not something you can upload into the database yourself.

To start you would delete the example rows. When filling out columns like connection type names should match the dropdown lists that appear here: https://openchargemap.org/site/poi

There are other more technical ways to arrange imports, especially if the import will ever be repeated but these require software development or scripting.

**Comment by aa0d** [comment]
[ocm_import_template.xlsx](https://github.com/openchargemap/ocm-system/files/4291858/ocm_import_template.xlsx)

I filled out the rows with a script, i hope the format is correct. I assume the column "number of points" means the number of outlets?

**Comment by webprofusion-chrisc** [comment]
Hi, thanks that looks pretty good, Number Of Points is actually number of usable stations or bays (just badly named) - so if a site can be used by two people at a time that would be 2.

Do you represent IONITY and if not where does the data come from?

**Comment by aa0d** [comment]
I'm currently working together with IONITY in a project. We are using OCM for a routing service and were supplied with the charging locations by IONITY.

**Comment by webprofusion-chrisc** [comment]
Thanks, so it's not clear if you have permission to commit this data to Open Charge Map on behalf of the data source (Ionity). 

We need to be strict on data copyright unfortunately, so we either need explicit permission from Ionity or the data needs to be individually crowdsourced without being copied from the original.

**Comment by aa0d** [comment]
I have been in contact with IONITY regarding the source and license of the data that I uploaded. The charging locations provided in the Excel sheet correspond to the Google Maps coordinates that are publically shown on www.ionity.eu. I was told that since the data is available publically, no license is required to provide the data to OCM.

**Comment by aa0d** [comment]
I guess the progress on this topic as come to a halt due to the Corona situation. I would still like to commit the stations however. Is there a way to contact you, in order to solve the situation with the license?

**Comment by webprofusion-chrisc** [comment]
Hi, thanks if you could forward the comments from Ionity to christopher.cook(at)openchargemap.net - I just need a record of the decision that can be attributed to them if required.

**Comment by webprofusion-chrisc** [comment]
@aa0d  I was unable to reply to your email but these have been imported now, many of the items where already there (the POIs we have may not all be associated with Ionity, we don't import anything that's on top of (or very close to) something we already have because they are inevitably mostly duplicates).

Attached is the raw POI file that resulted from the import, which we then de-duplicate and cross reference before importing. You can also loading this POI file as a layer in the app (enable Advanced options under settings, then reload and choose Add Layer from the menu).
