### ISSUE TITLE
Translation / localization of API strings

### ISSUE THREAD

**Issue by stanvass** [openchargemap/ocm-system#166]
I can't see a parameter that allows me to localize/translate the POI details (to German, for example). Is this a feature? I see old discussions about it, but I see no parameters in the documentation. What would be the recommended approach here?

**Comment by webprofusion-chrisc** [comment]
Hi, I'm not really sure what you mean? The API data field names are fixed and not translatable if that's what you mean (they are a direct serialization of our object model) - you can of course call them anything you like in a UI.

**Comment by stanvass** [comment]
Hi,

Not field names, but UI strings under "Title" as seen throughout the core reference data for things like charger types, connection types, check-in types, etc.: https://api.openchargemap.io/v3/referencedata/ Ideally also the charging point comments, although I could see how that won't work if the submitter provides no translation. But at least the general purpose collections.

Thanks.

**Comment by webprofusion-chrisc** [comment]
UI localisations can be found here, however they are community maintained and not regularly updated:
https://github.com/openchargemap/ocm-app/tree/master/src/assets/i18n

**Comment by webprofusion-chrisc** [comment]
Updated topic on app localisation plans:

https://github.com/openchargemap/ocm-app/issues/35
