### ISSUE TITLE
Web / App map : some charge locations are not being displayed

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#167]
on map.openchargemap.io or the android app, with all filters off, search for location: Reading, Reading, England, United Kingdom

using developer tools, look at the network request, which shows the json returned from the /v3/poi call.

POI 126915 (The Oracle Shopping Centre-the Riverside Car Park) is in the result set, but not displayed.

**Comment by baryluk** [comment]
Displays for me:

![Screenshot at 2020-10-20 13-04-27](https://user-images.githubusercontent.com/110322/96589829-d0c6fa80-12d4-11eb-9b7a-7010afbeb09e.png)
