### ISSUE TITLE
Extremally poor utilisation of space in browser map

### ISSUE THREAD

**Issue by baryluk** [openchargemap/ocm-system#168]
![Screenshot at 2020-10-15 20-09-47](https://user-images.githubusercontent.com/110322/96181255-3efd6d00-0f23-11eb-8a98-cf40396859c2.png)

Only 34% of available space is utilized.

I am pretty sure this can be upped to 90%, maybe 95%.

Inspecting HTML, it looks there is a hardcoded size of the iframe: `style="width:100%;height:600px"`

**Comment by webprofusion-chrisc** [comment]
Thanks, yes, of course on my 1080 high display it looks great :)

I think to do that properly we'd need to get rid of the other front page content so we can fill the remaining height?

https://map.openchargemap.io is the real map site, as you can probably tell the iframed version is kind of a second class citizen on that front page.

**Comment by webprofusion-chrisc** [comment]
Ok, I've removed the bottom content that nobody reads anyway and removed some of top padding and the old Add link (people should generally use the map/app to add locations now). See what you think.

**Comment by baryluk** [comment]
Yes, beautiful. Thank you!
