### ISSUE TITLE
POI API request returns charging locations on corners of map (Google Maps)

### ISSUE THREAD

**Issue by sarwech** [openchargemap/ocm-system#194]
Hi there 👋 

I'm working on an app which gets OCM data and plots it in Google Maps. When zoomed in, the charging locations that get returned are spread across the map nicely.

At a certain zoom level, however, there are no charging locations in the middle and instead they're all bounded towards the corners of the map. See below.

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/13512990/160137415-a6592e60-487b-4b6b-8009-000a67670ff9.png">

The API request looks like this:

`https://api.openchargemap.io/v3/poi/?output=json&countrycode=GB&maxresults=50&compact=false&camelcase=true&verbose=false&includecomments=true&key=${API_KEY}&opendata=true&boundingbox=(${north}%2C${west})%2C(${south}%2C${east})`

Am I doing something wrong here? How would I request charging locations where they can be spread more evenly, or at least start from the centre?

Thanks!

**Comment by webprofusion-chrisc** [comment]
Hi, when you limit the results to 50 what happens is the query just returns the first 50 results within the bounding box, in the order that they appear in the database spatial index (which is not random).

**Comment by sarwech** [comment]
Hi Christopher, appreciate the reply. I limited the results so as not to
overload the API. What would you recommend increase the limit to?

**Comment by webprofusion-chrisc** [comment]
As an example London is a bit extreme (it has hundreds of low power charging points in a very small area), so I would probably use 250 (max 500). The key to helping not overload the API is to cache your results (or remember your last query) so you don't call the same query twice in a row, and to throttle (or debounce) your query requests so you don't call the API multiple times per second as the user moves the map.
