### ISSUE TITLE
Latitude and longitude in location form

### ISSUE THREAD

**Issue by doonser** [openchargemap/ocm-system#199]
Is it necessary to require latitude and longitude in your form to add a new location? Isn't a street address enough? If I'm on the road and want to add a location, it's going to take a lot of fiddling on my phone to find the lat & long. Plus, your form label says, "If adding manually." Why require that level of detail? Or at least autofill them from a known source.

**Comment by webprofusion-chrisc** [comment]
Are you using https://map.openchargemap.io ? It has an address suggestion which auto populates all of the information. Yes lat/long is mandatory and is auto populated from the position you choose on the map.
