### ISSUE TITLE
Adding new operator doesn't allow it to be selected in editors (cacheing)

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#202]
This is probably affecting editors more than anyone else, but if we need to create a new operator, the list of operators is currently cached somewhere in a CDN, with quite a long expiry time, so when we go back an entry to assign the new operator to it, it's not in the drop-down, and won't be for many hours (days?)

Work-around: Make a note of the new operator's ID, then in the traditional web-based editor /site/poi/edit/ , use browser developer tools for force the selected ID in the OperatorInfo_ID field. Rather tedious.

**Comment by webprofusion-chrisc** [comment]
Closing as new operators should become available in the app search lookup within 5 minutes when cache refreshes the core reference data served by the API.
