### ISSUE TITLE
App does not allow me to Enter new Charger sites

### ISSUE THREAD

**Issue by rvergara** [openchargemap/ocm-system#207]
I have created several Charger sites before but during the last 4 or 5 weeks the app prompts that it is not posible to submit new sites at this time and i should try later. I can edit sites withit a problem but I can't submit new ones

**Comment by webprofusion-chrisc** [comment]
Thanks, are you entering a full address for the location? Are you using https://map.openchargemap.io or a mobile app?

**Comment by rvergara** [comment]
Thanks for your response.

I am using the android app and I am not entering an address but clicking at
the point where the chargers is on the map.

As I said before, I was able to submit new charger sites a few week ago but
now I am propted this alert message that the submit can not be completed at
this time. However I can edit chargers without a problem

Regards

Ramiro

**Comment by webprofusion-chrisc** [comment]
Our API now rejects submission that don't set the Address Line 1 or Line 2, Postcode and Country. You should be able to populate the nearest address information using the "Use This Address" button.

**Comment by rvergara** [comment]
Thanks,

That is what changed a few weeks ago, I just entered an address and I could
submit a charger site without a problem.

Problem solved!

Regards
