### ISSUE TITLE
Charger icons not pinned correctly (centered)

### ISSUE THREAD

**Issue by rrlevy** [openchargemap/ocm-system#208]
I noticed that the charger icons on the map are centered on the middle of the pin, and not the tip of the pin.

This gives the user wrong information about the location of the charger.

For example:

![image](https://user-images.githubusercontent.com/14061585/203801210-c645c861-2b5a-43ff-99aa-f3d2702a6070.png)
This view makes it look like that the charger is on the left bank of the river.

![image](https://user-images.githubusercontent.com/14061585/203801345-a52344d0-1164-4f60-952c-3d37a813468e.png)
However, if you Zoom In you will see that it's actually on the right bank.

This probably happens because the image for the icon used was cropped to contain only the actual image of the icon.

If you change the icons to add more vertical transparent pixels underneath it, so that the CENTER of the image is actually the tip of the pin, it should always appear correctly on the map.

For example, if the pin is 40x100 pixels, just resize the canvas to 40x200 and keep the current image aligned to the top. This should work.

**Comment by rrlevy** [comment]
I just made a search on the code base and found some icons:

This is one of them, they have 68x100 pixels and the tip is at 92 pixels from the top:
![set4_level3](https://user-images.githubusercontent.com/14061585/203803383-25241fa7-f429-4ece-b378-372379ad6689.png)

I just made a test that increased the canvas to 184 (92 x 2) making a 68x184 image:
![set4_level3_fixed](https://user-images.githubusercontent.com/14061585/203803864-36812536-ad36-45ed-92c7-cb441d2626cf.png)
Now the tip of the arrow is centered in the image and it should show up correctly on the map.

Can anyone that has the code running locally test if this will work plug an play just by replacing the image?

**Comment by webprofusion-chrisc** [comment]
This is now resolved by changing/standardising the icon anchor position.
