### ISSUE TITLE
UK National Charge Point Registry import is matching BP Pulse (AU) in preference to BP Pulse (UK)

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#220]
BP Pulse (AU) is a different charging network to BP Pulse (UK), credentials for one don't work on the other.

When matching charging network names against the UK National Charge Point Registry, it should perhaps favour operator name matches with a (UK) suffix over a less appropriate substring match?

This probably also affects other imports for other countries, especially when there's multinational entities branding disjoint networks as though they were one.

Example:

OCM-255435

**Comment by webprofusion-chrisc** [comment]
Agreed, we also have a direct mapping of Name: OCM-OPERATOR-ID that's a bit less haphazard than the old method of guessing the names, it just doesn't work dynamically when we add new operators to our database.

**Comment by webprofusion-chrisc** [comment]
As an aside, we only have 6 imports, 3 of which are OCPI feeds - currently my plan would be to retire any other imports as soon as an OCPI feed becomes available as an alternative. I'm pretty sure the US AFDC will move to an OCPI feed sometime as they are proposing to mandate an OCPI feed to them from networks (which is something all countries should have!). 

Long term I'd be happy to import only OCPI and even make our main API be an OCPI (locations) output but there's plenty of gaps to fill and in the case of UK CPR we'd have to encourage them to offer an OCPI version of their API (feel free to do that if you know anyone!).

The main problem we have with matching imports to operators currently is we don't get a feed of operators so we have to manually add them to our database and match them as a mapping in code.

**Comment by webprofusion-chrisc** [comment]
Updated the operator mappings but I see we are also getting null Titles for some times so I'll investigate that and apply some combination of what you suggested in #156

**Comment by zymurgic** [comment]
It doesn't help that the UK National Chargepoint registry seems to offer charge point operators a bulk import, but offers nothing to aid in automatically synchronising the existing entries with their own systems, so there's a lot of entries in there that are missing important information, like accurate charge connector information; or the entries have long-since been defunct, with charge points that no longer exist, or have been replaced with upgraded equipment.
