### ISSUE TITLE
"Connections" field missing in CSV response?

### ISSUE THREAD

**Issue by jumpjack** [openchargemap/ocm-system#221]
Using this link, in the retrieved data there are no data about power:

`https://api.openchargemap.io/v2/poi/?output=csv&countrycode=IT&maxresults=10`

But I get them using JSON as output, in "Connections" field:

`https://api.openchargemap.io/v2/poi/?output=json&countrycode=IT&maxresults=10`

**Comment by webprofusion-chrisc** [comment]
Thanks, our (legacy) CSV output is unable to provide specifications pre-dates our inclusion of kW. We don't currently intend to expand on the CSV fields because it can break existing consumers.

**Comment by webprofusion-chrisc** [comment]
Is there anything in our documentation that made you use v2 of the AI instead of v3?

**Comment by jumpjack** [comment]
> Is there anything in our documentation that made you use v2 of the API instead of v3?
> 
> https://openchargemap.org/site/develop/api

No, I am updating a web page I wrote several years ago, I didn't notice I was using an old version.


> Thanks, our (legacy) CSV output is unable to provide specifications pre-dates our inclusion of kW. 

Sorry, I don't understand your reply (I'm not native English speaker): can V3 provide kW data in some way? I still don't get such data using https://api.openchargemap.io/v3/poi/?output=csv&countrycode=IT&maxresults=10

I'd like to use CSV rather than JSON because response is much shorter... but apparently it's shorter because it lacks most important datum! :-(

**Comment by webprofusion-chrisc** [comment]
We are not planning to add any more functionality to our CSV output. Please use the JSON output.
