### ISSUE TITLE
readme updates - dev environment setup and forms of communication

### ISSUE THREAD

**Issue by BarnacleJones** [openchargemap/ocm-system#224]
Hi I am looking to start contributing to this project.

I am encountering issues while getting the project running and thought a good first contribution would be to update the readme with more up to date and detailed instructions on environment setup, and getting started guide to contributing to the project. 

Also there is no indication on the readme of the preferred form of communication, be it making issues like this or if there are official chat channels, so I can update that too once I know.

I should note, I am new to open source contribution, so apologies if this is obvious information. 

Creating an issue to check how communication is preferred and if this enhancement would be worthwhile.

**Comment by webprofusion-chrisc** [comment]
Hi, if you visit our website you will see we have a community forum. https://community.openchargemap.org/ this can be used for broad discussions on any related topic.

If you have a bug to fix or a change to propose please do open an issue and provide details. Don't submit extensive PRs without starting a discussion or issue first as these will definitely lead to disappointment and wasted effort and that applies to interaction with all open source projects. You can generally assume that any mature project as already thought about things along the lines of whatever change you might be planning and can provide feedback/direction on the idea.

**Comment by BarnacleJones** [comment]
Fantastic, appreciate the input. 
After creating this issue and another couple of hours of work I realise my holdup was the readme saying .net 6xx but project looks like it recently updated to .net 8. Therefore it just took getting most recent SDK and updating to the preview version of visual studio to fix the issues. 
Therefore I will close this issue, as beyond that I don't have anything to add. Thanks again.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes if you find that the guidance needs to be updated please submit a PR for that, however .net 8 will come out in early November so it won't require a preview anymore.
