### ISSUE TITLE
maximum number of connectors / maximum number of bays of 100 is too low

### ISSUE THREAD

**Issue by zymurgic** [openchargemap/ocm-system#229]
There are a growing number of charging locations where an entire car park is outfitted with charging bays, in which case a limitation of 100 connectors or 100 bays is too low.

An example of this is https://openchargemap.org/site/poi/details/194034, which was created before the limitation was put in place. It now needs to be edited to reflect a change, but neither the main website version, or the mobile app will accept the reality of having 158 charging connectors in one place (down two from the previous 160).

**Comment by webprofusion-chrisc** [comment]
Thanks, Simon, I've boosted that to 500 now, is that enough?
