### ISSUE TITLE
Translation: Cookie consent and privacy settings should be translated in UI

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#45]
The following parts need to be made translateable:
![15cookies_02](https://cloud.githubusercontent.com/assets/9208139/10498477/d70c257c-72cb-11e5-83f7-2c0af0fe4e0b.PNG)

![15privacy_settings_02](https://cloud.githubusercontent.com/assets/9208139/10498483/db5126aa-72cb-11e5-83ff-541238f3f6c1.PNG)

**Comment by webprofusion-chrisc** [comment]
Needs investigation, we are using a 3rd party cookie consent widget.

**Comment by webprofusion-chrisc** [comment]
Closing all translation related items. We lack sufficient project resources to translate all of our UI.
