### ISSUE TITLE
Translation: Menu items should be translated in UI

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#46]
The following part of menu still needs to be made translateable:
![15menu_items](https://cloud.githubusercontent.com/assets/9208139/10498827/2e10c480-72cd-11e5-88b4-ec22163312d1.PNG)

**Comment by solarpete** [comment]
Since this issue is very small, the following page can be fixed together with it:

![image](https://cloud.githubusercontent.com/assets/9208139/10560705/9cf534a6-7513-11e5-9591-9f269e8b8597.png)

**Comment by solarpete** [comment]
Chris, how do you make the following code translatable?
@Html.ActionLink("Contact Us","Contact","About")

I would like to finally learn it, since it is present not only in the untranslated part of the menu and on the GeneralError page, but also quite frequently in other places.

**Comment by webprofusion-chrisc** [comment]
@Html.ActionLink("Contact Us","Contact","About") can be made translatable by including the optional HTML Attribute parameter:
@Html.ActionLink("Contact Us", "Contact", "About", new { data_localize = "ocm.general..." })
Note that MVC then transforms the data_localize to data-localize when it renders the HTML. 

The alternative is to convert the link to a normal <a> tag using a Url helper for the action (link gets generated pointing to the Contact method of the About controller):
<a href="@Url.Action("Contact","About")" data-localize="ocm.general...">Contact Us</a>

**Comment by webprofusion-chrisc** [comment]
We currently don't have a way to change the page title, it would be something that loaded the json language file on the server side rather than in the client browser and applied it as a Resource. This would actually be better from an ASP.net/MVC point of view but at the moment we re-use the javascript based translation mechanism.
