### ISSUE TITLE
Translation: Browse all locations page should be translated in UI

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#47]
The following parts of the page still need to be made translateable:

![15browse_all_locations_02](https://cloud.githubusercontent.com/assets/9208139/10499263/9a8bb406-72cf-11e5-80f6-584c19baa479.PNG)

**Comment by solarpete** [comment]
Is the fact that you can see fewer filtering criteria when viewing the Browse all locations page in a smaller window bug or a feature?

It looks something like this (which is really a fraction of what you can see with a maximized window as in the comment above):

![15browse_all_locations](https://cloud.githubusercontent.com/assets/9208139/10499361/161b42d0-72d0-11e5-8c01-87830b57adc3.PNG)

**Comment by webprofusion-chrisc** [comment]
This is intentional, whether or not its the right thing to do is another question. The problem is that mobile users would otherwise not see any results without a lot of scrolling.

**Comment by solarpete** [comment]
I understand. I had a hunch it was intentional. 

It could be probably improved by allowing the user to expand the hidden filters, but since it is probably not so important I don't know whether it deserves its own enhancement issue.

**Comment by solarpete** [comment]
I forgot to mark the following text that is not made translatable:

![15browse_all_locations_03](https://cloud.githubusercontent.com/assets/9208139/10557872/30978328-74bd-11e5-86d6-43d9532a01ff.PNG)
