### ISSUE TITLE
API: Implement API for (near)real-time status polling (if available)

### ISSUE THREAD

**Issue by webprofusion-chrisc** [openchargemap/ocm-system#52]
Some data providers make near-realtime status information available. We need to provide a single API which consolidates status info from a range of networks. Apps should be able to query per POI or based on a lat/long and optional network provider etc.

Realtime status is a long standing issue which has been asked for since OCM started. Progress would ideally start with a small number of data providers and a design for a common querying approach and common result set (normalising the way the various data providers present this data). Data licensing issues also apply.

**Comment by JinaJita** [comment]
Is this still relevant? I would really like such an API extension too. I probably could implement it, but only if you approve and there is a chance it will be accepted as a pull request.

**Comment by webprofusion-chrisc** [comment]
@JinaJita thanks, I can't predict if we would accept the PR but any effort it much appreciated. Then general criteria would be:
- The solution is not just the API design, it's how we get the data (push/pull/storage/querying)
- We must be allowed to use the data (open data license etc)
- An efficient storage and update process 
- Support for many providers (writing an export for one data provider/website is very easy, managing many efficiently is more difficult).

This generally would need a separate scalable service/cloud web job type solutions. If you imagine we may be updating data from hundreds of providers around the world (or they may be streaming/pushing data to us). Then we need to aggregate and provide fast query mechanism, ideally also with a historian function to capture usage/reliability statistics. You can maybe see why I haven't gotten around to it yet.
