### ISSUE TITLE
Route planning?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [openchargemap/ocm-system#54]
The ability to enter a start and end point of a route and see the charging stations most relevant is a feature most people expect to see. Several community and commercial efforts exist in this sphere and this is not a proposal to compete on sophistication, only basic functionality to avoid users having to hunt for a services which use current OCM data.

Should we implement anything in this space or leave it to other projects?

**Comment by webprofusion-chrisc** [comment]
Relates to favourites/journey planning: https://github.com/openchargemap/ocm-system/issues/31

**Comment by mkrasselt1** [comment]
i cloud possibly help with that since i created evpaths.app and wnat to change my datasource to ocm now. but its api is quite complicated :/

**Comment by webprofusion-chrisc** [comment]
@mkrasselt1 I did add a basic route planner to the ocm app (set a start/end point and find route using Google directions API then search for POIs along the route) but I removed it for now as the Google API was costing us and the functionality wasn't very mature.

**Comment by webprofusion-chrisc** [comment]
Closing for now. A Better Route Planner already does this well and has the user mind-share.
