### ISSUE TITLE
Translation: The Sign in page should be translated in UI

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#72]
All parts of the page still need to be made translateable:

![15sign_in_2](https://cloud.githubusercontent.com/assets/9208139/10559019/ac994550-74e6-11e5-8b05-e802cf70b4ad.PNG)

**Comment by solarpete** [comment]
Suggestion: Don't apply translations to the "Sign In with Twitter" and "Sign In with Facebook" and just remove the string "Sign in with".

The "Open Charge Map" part of "Open Charge Map - Sign In" string can be probably removed as well.

**Comment by webprofusion-chrisc** [comment]
Yes, I agree that the redundant 'Sign in with..' and 'Open Charge Map -' can be removed.
