### ISSUE TITLE
App: The link to website on a charging location info is incorrect.

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#84]
The link to a website on a charging location info page for a charging station in WebApp is incorrect, even though it displays correctly. Instead of the displayed text the link points to the WebApp itself:
![web_app_bad_link_02](https://cloud.githubusercontent.com/assets/9208139/10715124/50580f54-7b0a-11e5-98f2-b667a15a250c.png)

**Comment by solarpete** [comment]
Actually this happens only when I try to open the link in a new tab (in Chrome and Firefox browsers).

**Comment by webprofusion-chrisc** [comment]
This is intentional, actually what's happening is the href of the link points to the same page but the click handler opens the target link instead. This is so that when the app is running under Apache Cordova (on Android/iOS) the link opens using a new system browser rather than within the app.
