### ISSUE TITLE
Missing Edit Queue information or incorrectly generated Subscription Notification email

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#91]
I received this Subscription Notification email 
![image](https://cloud.githubusercontent.com/assets/9208139/12901159/5bf53b6c-ceba-11e5-9150-87d9b728e5a1.png)
with the following details:
![image](https://cloud.githubusercontent.com/assets/9208139/12901144/45809494-ceba-11e5-8219-56173930a63d.png)

However when I attempt to check out the changes for this location by searching for the locations ID on the Edit Queue page with the following setting (search done on 8th of February 2016), I find no entry:
![image](https://cloud.githubusercontent.com/assets/9208139/12901276/0ab14236-cebb-11e5-83d3-64bf80b2a31c.png)

(All times are UTC+1)

**Comment by webprofusion-chrisc** [comment]
I believe this is caused when there are too many edits in the time frame being queried as the page will return a maximum of 200 results. If you set the date range to 05/02/2016 to 06/02/2016 you should see the edit. I will update the page to include a notice about the max results.

**Comment by webprofusion-chrisc** [comment]
As a separate item we need to allow searching on the history of a specific location ID. That would make this type of search easier.

**Comment by webprofusion-chrisc** [comment]
You can now search on a specific OCM-ID (to a maximum of 90 days history, thereafter the info may be in archive):
http://openchargemap.org/site/editqueue?id=57649&showprocessed=true&showeditsonly=false
