### ISSUE TITLE
API: KML output syntax error

### ISSUE THREAD

**Issue by dexterbg** [openchargemap/ocm-system#98]
Fetching the german POI in KML format currently results in an invalid KML file. Google Earth simply crashes on loading it, gpsbabel gives the hint needed to find the problem:

> garmin_gpi: Unsupported speed unit 'Work GmbH' in item 'Work GmbH'!

Looking for "Work GmbH" I found this item:

`... <Placemark id="OCM-64525"><name>LAN@Work GmbH</name> ...`

The "@" appears to cause the problem, replacing it by "-at-" solves the issue.

**Comment by webprofusion-chrisc** [comment]
Thanks we need to make sure we're escaping titles etc. Having said that, how useful is the kml output? Our json feed is the most detailed.

**Comment by dexterbg** [comment]
KML is currently the only POI standard format of the API. KML can be converted directly to other POI formats (for example using gpsbabel) to create files suitable for navigation systems. So it's very useful, and it doesn't need more detail.

**Comment by webprofusion-chrisc** [comment]
Looking into this, I've updated the way we escape titles however @ appears to be perfectly valid text inside an XML element as does not appear to be a special character which should be escaped.

**Comment by dexterbg** [comment]
I also did not find any reference of "@" being special in KML. Apparently, my Google Earth also today no longer crashes on loading the KML file, so this seems to be rather a gpsbabel issue. Sorry for bothering you.

**Comment by dexterbg** [comment]
Confirmed, it's gpsbabel trying to read a speed alert from "@...".
